### ISSUE TITLE
gview cannot read prokka annotatated sequence

### ISSUE THREAD

**Issue by flannsmith** [phac-nml/gview#3]
```
 java -jar gview.jar -i E5b_S84.gbk -s example_styles/basicStyle.gss -l linear -v
ca.corefacility.gview.data.readers.GViewDataParseException: For file file:/home/linda/Downloads/gview/E5b_S84.gbk
        at ca.corefacility.gview.data.readers.StandardSequenceFormatReader.read(Unknown Source)
        at ca.corefacility.gview.data.readers.GViewFileReader.read(Unknown Source)
        at ca.corefacility.gview.map.GViewMapFactory.createMap(Unknown Source)
        at ca.corefacility.gview.main.GViewMain.main(Unknown Source)
Caused by: ca.corefacility.gview.data.readers.GViewDataParseException: org.biojava.bio.BioException: Could not read sequence
        at ca.corefacility.gview.data.readers.StandardSequenceFormatReader.read(Unknown Source)
        ... 4 more
Caused by: org.biojava.bio.BioException: Could not read sequence
        at org.biojavax.bio.seq.io.RichStreamReader.nextRichSequence(RichStreamReader.java:113)
        ... 5 more
Caused by: org.biojava.bio.seq.io.ParseException: 

A Exception Has Occurred During Parsing. 
Please submit the details that follow to biojava-l@biojava.org or post a bug report to http://bugzilla.open-bio.org/ 

Format_object=ca.corefacility.gview.data.readers.GenbankFormatModified
Accession=
Id=null
Comments=Bad section
Parse_block=
Stack trace follows ....


        at ca.corefacility.gview.data.readers.GenbankFormatModified.readSection(Unknown Source)
        at ca.corefacility.gview.data.readers.GenbankFormatModified.readRichSequence(Unknown Source)
        at org.biojavax.bio.seq.io.RichStreamReader.nextRichSequence(RichStreamReader.java:110)
        ... 5 more
Caused by: java.lang.NullPointerException
        ... 8 more


```
```

This is the contents of the prokka annotated gbk file:

LOCUS       E5b_S84_NODE_16187      1941 bp    DNA     linear       18-FEB-2021 

DEFINITION  Genus species strain strain. 

ACCESSION    

VERSION 

KEYWORDS    . 

SOURCE      Genus species 

  ORGANISM  Genus species 

            Unclassified. 

COMMENT     Annotated using prokka 1.13 from
            https://github.com/tseemann/prokka

FEATURES             Location/Qualifiers
     source          1..1941
                     /organism="Genus species"
                     /mol_type="genomic DNA"
                     /strain="strain"
     CDS             458..1849
                     /locus_tag="GGMHPMLN_00001"
                     /inference="ab initio prediction:Prodigal:2.6"
                     /inference="similar to AA
                     sequence:viral_proteins_plus_crass.fa:YP_002290918.1"
                     /codon_start=1
                     /transl_table=11
                     /product="putative phage site-specific recombinase
                     [Clostridium virus phiCD27]"
                     /translation="MKTTEFTPAVRIAAYIRVSTEEQAVHGLSIGAQRDALEAWAAQN
                     QVRIVDCYIDAGISARKPASKRPELQRLLADVRAGKIDQIVFTKLDRWFRNIAEYYKV
                     QEILEAHRVDWRTIHEDYDTSTASGRLKINIMLSVAQDEADRTSERIKAVFDAKKERR
                     EPCTGKVPTGYKIEGKKIVKDPESEAAVACFFESFLECRSIEKARRKVQERFGVLYSY
                     YLARNMLYKEAYYGRFEGVDDMCPAYITKAQYDEICANRRRTERKANADRVYLFTGLI
                     FCPQCGRRFGAHTNVYTKKSGAVNDGIAYNCRGRYNNGDCINGVNVRECVIESYLLEN
                     VDAELEKLAFEMERSASADQPVRNYTQERARLQKKLSRLKDLYVDDIIDLELYRKDYE
                     ALSAQLDSLLIEERESAATRPSTERLRSILSYGWQDMYAALSRADQQAFWRSVLDRIL
                     IYPTRQITISFRF"
ORIGIN      
        1 aaacatagaa agggcgctgc cggtatacgg ttggccccca gaagttatct caaagagtaa
       61 ccgctggttt ggttggccgg gcggttactt ctttttattg gccgcaataa agaggccgat
      121 aatgccgatg ataacaagtg tgtactgaaa cagttcactg tatgtgacca ttgggcagcc
      181 cccctttccg aaaatcaggg ggcaagaagc gccccccgtt aagagggctt caccgcctac
      241 cgttactggc agcgctgaaa gataattctt tcctgcactc aggatagcac aggctttgac
      301 aaaatgcaat gaaaatccca aacgtctggg attttgggca atcagaaacc gcccctggca
      361 ctgaagcacc aaggacggtt caaggagcag taaacttcgc cgggatactg ctccttcatt
      421 gtaatgcaga tttcagaaaa atacaaggag gaaatttatg aaaacaactg aatttacccc
      481 ggcagtccgg atcgcggcct acatccgcgt ctccacagag gagcaggcgg tccacgggct
      541 gtccatcggg gcccagcggg atgcgctgga ggcctgggcg gcgcagaacc aggtgcggat
      601 tgtggactgc tacatcgacg ctggtatctc cgcccggaag cccgcctcaa aacgcccgga
      661 gcttcagcgg ctgctggcgg acgttcgcgc cgggaagatc gatcagatcg tctttaccaa
      721 gctggaccgc tggttccgta acattgcgga gtattacaag gtgcaggaga ttctggaggc
      781 ccatcgtgtg gactggcgga ccatccacga ggactacgac acctctactg cctccggccg
      841 tctgaagatc aacattatgc tctcggtagc ccaggacgag gcggaccgca ccagcgaacg
      901 aatcaaggcg gtgttcgacg ccaagaagga acgccgggag ccctgcaccg ggaaagtgcc
      961 cacgggttac aaaatcgagg gaaagaagat cgtcaaggac ccggagtcag aggccgcggt
     1021 cgcctgcttc tttgaaagct ttctggaatg caggtcgatc gaaaaagccc ggcggaaggt
     1081 ccaggagcgc tttggcgtac tgtactctta ctatctggcc cggaacatgc tgtataaaga
     1141 ggcgtattat ggacgcttcg agggcgtgga tgatatgtgc ccggcgtata tcaccaaagc
     1201 gcaatatgat gagatttgtg cgaaccgccg ccggaccgag cggaaggcga acgcagaccg
     1261 ggtctattta tttaccggac tcattttctg tcctcagtgc ggacggcggt ttggcgccca
     1321 cacaaatgta tacaccaaaa agtccggggc ggtaaatgac ggtatcgctt acaactgccg
     1381 gggtaggtat aacaacggcg attgtatcaa cggcgtaaat gttcgtgagt gtgtgattga
     1441 gagctatctt ctggaaaacg ttgacgctga gttggagaag ctggcttttg agatggaacg
     1501 gtctgcgtcc gcagaccagc cggtcaggaa ttacacgcag gaacgggcca gactgcaaaa
     1561 gaaactttcc cgcttgaaag atttgtatgt tgatgatata attgacctgg agctgtaccg
     1621 gaaagattat gaagctttaa gcgcccagtt agattcgctg ctgatagagg aacgggaatc
     1681 cgcagccaca cgccccagca cagaacggct gcgctcgatt ttgtcgtacg gctggcagga
     1741 tatgtacgct gccttgagcc gggccgacca gcaggcgttc tggcgttcgg tgcttgaccg
     1801 aatccttatt tatcccactc ggcaaatcac aatatctttt cggttttaat tttttagaaa
     1861 atttcataca taaatttaat agaccagtgg gaatcccgcc ccatttccga aagcgtttcc
     1921 agatttcaat ggtataggcg g
//




```

**Comment by flannsmith** [comment]
File works if first few lines of formatting removed from prokka gbk file! 


LOCUS       E5b_S84_NODE_16187      1941 bp    DNA     linear       18-FEB-2021 


FEATURES             Location/Qualifiers
     source          1..1941
                     /organism="Genus species"
                     /mol_type="genomic DNA"
                     /strain="strain"
     CDS             458..1849
                     /locus_tag="GGMHPMLN_00001"
                     /inference="ab initio prediction:Prodigal:2.6"
                     /inference="similar to AA
                     sequence:viral_proteins_plus_crass.fa:YP_002290918.1"
                     /codon_start=1
                     /transl_table=11
                     /product="putative phage site-specific recombinase
                     [Clostridium virus phiCD27]"
                     /translation="MKTTEFTPAVRIAAYIRVSTEEQAVHGLSIGAQRDALEAWAAQN
                     QVRIVDCYIDAGISARKPASKRPELQRLLADVRAGKIDQIVFTKLDRWFRNIAEYYKV
                     QEILEAHRVDWRTIHEDYDTSTASGRLKINIMLSVAQDEADRTSERIKAVFDAKKERR
                     EPCTGKVPTGYKIEGKKIVKDPESEAAVACFFESFLECRSIEKARRKVQERFGVLYSY
                     YLARNMLYKEAYYGRFEGVDDMCPAYITKAQYDEICANRRRTERKANADRVYLFTGLI
                     FCPQCGRRFGAHTNVYTKKSGAVNDGIAYNCRGRYNNGDCINGVNVRECVIESYLLEN
                     VDAELEKLAFEMERSASADQPVRNYTQERARLQKKLSRLKDLYVDDIIDLELYRKDYE
                     ALSAQLDSLLIEERESAATRPSTERLRSILSYGWQDMYAALSRADQQAFWRSVLDRIL
                     IYPTRQITISFRF"
ORIGIN      
        1 aaacatagaa agggcgctgc cggtatacgg ttggccccca gaagttatct caaagagtaa
       61 ccgctggttt ggttggccgg gcggttactt ctttttattg gccgcaataa agaggccgat
      121 aatgccgatg ataacaagtg tgtactgaaa cagttcactg tatgtgacca ttgggcagcc
      181 cccctttccg aaaatcaggg ggcaagaagc gccccccgtt aagagggctt caccgcctac
      241 cgttactggc agcgctgaaa gataattctt tcctgcactc aggatagcac aggctttgac
      301 aaaatgcaat gaaaatccca aacgtctggg attttgggca atcagaaacc gcccctggca
      361 ctgaagcacc aaggacggtt caaggagcag taaacttcgc cgggatactg ctccttcatt
      421 gtaatgcaga tttcagaaaa atacaaggag gaaatttatg aaaacaactg aatttacccc
      481 ggcagtccgg atcgcggcct acatccgcgt ctccacagag gagcaggcgg tccacgggct
      541 gtccatcggg gcccagcggg atgcgctgga ggcctgggcg gcgcagaacc aggtgcggat
      601 tgtggactgc tacatcgacg ctggtatctc cgcccggaag cccgcctcaa aacgcccgga
      661 gcttcagcgg ctgctggcgg acgttcgcgc cgggaagatc gatcagatcg tctttaccaa
      721 gctggaccgc tggttccgta acattgcgga gtattacaag gtgcaggaga ttctggaggc
      781 ccatcgtgtg gactggcgga ccatccacga ggactacgac acctctactg cctccggccg
      841 tctgaagatc aacattatgc tctcggtagc ccaggacgag gcggaccgca ccagcgaacg
      901 aatcaaggcg gtgttcgacg ccaagaagga acgccgggag ccctgcaccg ggaaagtgcc
      961 cacgggttac aaaatcgagg gaaagaagat cgtcaaggac ccggagtcag aggccgcggt
     1021 cgcctgcttc tttgaaagct ttctggaatg caggtcgatc gaaaaagccc ggcggaaggt
     1081 ccaggagcgc tttggcgtac tgtactctta ctatctggcc cggaacatgc tgtataaaga
     1141 ggcgtattat ggacgcttcg agggcgtgga tgatatgtgc ccggcgtata tcaccaaagc
     1201 gcaatatgat gagatttgtg cgaaccgccg ccggaccgag cggaaggcga acgcagaccg
     1261 ggtctattta tttaccggac tcattttctg tcctcagtgc ggacggcggt ttggcgccca
     1321 cacaaatgta tacaccaaaa agtccggggc ggtaaatgac ggtatcgctt acaactgccg
     1381 gggtaggtat aacaacggcg attgtatcaa cggcgtaaat gttcgtgagt gtgtgattga
     1441 gagctatctt ctggaaaacg ttgacgctga gttggagaag ctggcttttg agatggaacg
     1501 gtctgcgtcc gcagaccagc cggtcaggaa ttacacgcag gaacgggcca gactgcaaaa
     1561 gaaactttcc cgcttgaaag atttgtatgt tgatgatata attgacctgg agctgtaccg
     1621 gaaagattat gaagctttaa gcgcccagtt agattcgctg ctgatagagg aacgggaatc
     1681 cgcagccaca cgccccagca cagaacggct gcgctcgatt ttgtcgtacg gctggcagga
     1741 tatgtacgct gccttgagcc gggccgacca gcaggcgttc tggcgttcgg tgcttgaccg
     1801 aatccttatt tatcccactc ggcaaatcac aatatctttt cggttttaat tttttagaaa
     1861 atttcataca taaatttaat agaccagtgg gaatcccgcc ccatttccga aagcgtttcc
     1921 agatttcaat ggtataggcg g
//
