### ISSUE TITLE
gview cannot read a prokka-generated gff file

### ISSUE THREAD

**Issue by reymonera** [phac-nml/gview#4]
Hi,

I have some problems to generate a circular map from my sequence and annotated data. This is what I obtain executing the `head` command on my .gff file:

```
##gff-version 3
##sequence-region CP010401.1 1 1467695
CP010401.1	Prodigal:002006	CDS	81	191	.	+	0	ID=NNIEBLHK_00001;inference=ab initio prediction:Prodigal:002006;locus_tag=NNIEBLHK_00001;product=hypothetical protein
CP010401.1	Prodigal:002006	CDS	199	540	.	+	0	ID=NNIEBLHK_00002;inference=ab initio prediction:Prodigal:002006;locus_tag=NNIEBLHK_00002;product=hypothetical protein
CP010401.1	Aragorn:001002	tRNA	618	707	.	-	.	ID=NNIEBLHK_00003;inference=COORDINATES:profile:Aragorn:001002;locus_tag=NNIEBLHK_00003;product=tRNA-Ser(gga)
CP010401.1	Prodigal:002006	CDS	1042	3558	.	-	0	ID=NNIEBLHK_00004;inference=ab initio prediction:Prodigal:002006;locus_tag=NNIEBLHK_00004;product=hypothetical protein
CP010401.1	Prodigal:002006	CDS	4870	5124	.	-	0	ID=NNIEBLHK_00005;Name=rpmA;db_xref=COG:COG0211;gene=rpmA;inference=ab initio prediction:Prodigal:002006,similar to AA sequence:UniProtKB:Q6NDE9;locus_tag=NNIEBLHK_00005;product=50S ribosomal protein L27
CP010401.1	Prodigal:002006	CDS	5137	5610	.	-	0	ID=NNIEBLHK_00006;inference=ab initio prediction:Prodigal:002006;locus_tag=NNIEBLHK_00006;product=hypothetical protein
CP010401.1	Aragorn:001002	tRNA	5894	5983	.	+	.	ID=NNIEBLHK_00007;inference=COORDINATES:profile:Aragorn:001002;locus_tag=NNIEBLHK_00007;product=tRNA-Ser(cga)
CP010401.1	Prodigal:002006	CDS	6008	7666	.	-	0	ID=NNIEBLHK_00008;eC_number=5.3.1.9;Name=pgi;db_xref=COG:COG0166;gene=pgi;inference=ab initio prediction:Prodigal:002006,similar to AA sequence:UniProtKB:Q8YF86;locus_tag=NNIEBLHK_00008;product=Glucose-6-phosphate isomerase
```

And this is the error I'm getting after trying to use `java -jar gview.jar -i sequence02.fna -g sequence02.gff -l circular -W 1200 -H 900 -f png -o image.png`:

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:659)
	at java.util.ArrayList.get(ArrayList.java:435)
	at org.biojava.bio.program.gff3.GFF3Parser.createRecord(GFF3Parser.java:213)
	at org.biojava.bio.program.gff3.GFF3Parser.parse(GFF3Parser.java:166)
	at org.biojava.bio.program.gff3.GFF3Parser.parse(GFF3Parser.java:98)
	at ca.corefacility.gview.data.readers.GFF3Reader.injectGFFFeatures(Unknown Source)
	at ca.corefacility.gview.map.GViewMapFactory.createMap(Unknown Source)
	at ca.corefacility.gview.main.GViewMain.main(Unknown Source)
```

Thanks for any help you could give me. 

Regards,

**Comment by apetkau** [comment]
Hello @reymonera,

Have you tried opening up the gff file using the GView GUI (you can just run `java -jar gview.jar` to open it up)?

I am not sure what the error is. I tested out opening up the small fragment of the gff file you gave to me and it works. Note that you don't need `-i sequence02.fna` in this case as GView is only interested in coordinates of features (found in the GFF file) and does not use sequence data.

**Comment by apetkau** [comment]
Closing issue.
